
name: wedding_app
description: A Flutter wedding app for managing RSVPs
version: 1.0.0
environment:
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  cloud_firestore: ^5.6.7
  firebase_storage: ^12.4.6
  qr_flutter: ^4.1.0
  url_launcher: ^6.2.0
  pdf: ^3.10.4
  path_provider: ^2.1.1
  open_file: ^3.3.2
  share_plus: ^11.0.0
  http: ^1.1.0
  cupertino_icons: ^1.0.8
  flutter_web_plugins:
    sdk: flutter
  provider: ^6.1.1
  intl: ^0.20.2
  google_fonts: ^6.1.0
  cached_network_image: ^3.3.1
  flutter_cache_manager: ^3.3.1
  file_picker: ^10.1.9
  firebase_app_check: ^0.3.1+5
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
  
  # Wedding-themed fonts
  fonts:
    - family: Pacifico
      fonts:
        - asset: assets/fonts/Pacifico-Regular.ttf
    - family: DancingScript
      fonts:
        - asset: assets/fonts/DancingScript-Regular.ttf
        - asset: assets/fonts/DancingScript-Medium.ttf
          weight: 500
        - asset: assets/fonts/DancingScript-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/DancingScript-Bold.ttf
          weight: 700
          
  # Uncomment this section to add wedding-themed images
  assets:
    - assets/images/
