// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCH5oVTK2anjo2K11XX3lnbmWHbakKBYfg',
    appId: '1:457538979505:web:e861c7198f726e87f7c490',
    messagingSenderId: '457538979505',
    projectId: 'weddingp-9ffea',
    authDomain: 'weddingp-9ffea.firebaseapp.com',
    storageBucket: 'weddingp-9ffea.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHrcYHHxzafD1kFQmV4ygWvWIyVSaa0Sc',
    appId: '1:457538979505:android:58735fecf98f2714f7c490',
    messagingSenderId: '457538979505',
    projectId: 'weddingp-9ffea',
    storageBucket: 'weddingp-9ffea.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsWnJG2sMFw-yjtG69cCcsAOJNTfZ9Iyo',
    appId: '1:457538979505:ios:0c4b802961f8276ff7c490',
    messagingSenderId: '457538979505',
    projectId: 'weddingp-9ffea',
    storageBucket: 'weddingp-9ffea.firebasestorage.app',
    iosBundleId: 'com.example.weddingPlanner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsWnJG2sMFw-yjtG69cCcsAOJNTfZ9Iyo',
    appId: '1:457538979505:ios:0c4b802961f8276ff7c490',
    messagingSenderId: '457538979505',
    projectId: 'weddingp-9ffea',
    storageBucket: 'weddingp-9ffea.firebasestorage.app',
    iosBundleId: 'com.example.weddingPlanner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCH5oVTK2anjo2K11XX3lnbmWHbakKBYfg',
    appId: '1:457538979505:web:6d7c42109bc4231df7c490',
    messagingSenderId: '457538979505',
    projectId: 'weddingp-9ffea',
    authDomain: 'weddingp-9ffea.firebaseapp.com',
    storageBucket: 'weddingp-9ffea.firebasestorage.app',
  );
}
